### Teste para obter itens sem desconto
GET http://localhost:8080/pedido/sem-desconto
Accept: application/json

### Teste para obter itens com desconto
GET http://localhost:8080/pedido/desconto-maior
Accept: application/json

### Teste para obter todos os itens ordenados por valor unitário em ordem decrescente
GET http://localhost:8080/pedido/ordenado-valor-unit
Accept: application/json

### Teste para obter o produto mais vendido
GET http://localhost:8080/pedido/mais-vendido
Accept: application/json

### Teste para obter notas fiscais com mais de 10 unidades
GET http://localhost:8080/pedido/nf-mais-10-unidades
Accept: application/json

### Teste para obter notas fiscais com valor total maior que 500
GET http://localhost:8080/pedido/valor-total-maior-500
Accept: application/json